services:
  ryot-db:
    image: "postgres:18-alpine" # at-least version 15 is required
    restart: "unless-stopped"
    container_name: "ryot-db"
    volumes:
      - "postgres_storage:/var/lib/postgresql"
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_PASSWORD=postgres"
      # Defaults you can optionally override:
      # - "POSTGRES_DB=postgres"
      # - "POSTGRES_USER=postgres"

  ryot:
    image: "ignisda/ryot:v10" # or ghcr.io/ignisda/ryot:v10
    # pull_policy: "always"
    container_name: "ryot"
    restart: "unless-stopped"
    ports:
      - "8000:8000"
    environment:
      - "TZ=Europe/Amsterdam"
      - "DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres" # REQUIRED
      - "SERVER_ADMIN_ACCESS_TOKEN=28ebb3ae554fa9867ba0" # REQUIRED: set to a long random string
      # Optional configuration:
      # - "FRONTEND_URL=https://ryot.your-domain.com" # IP address is fine too

volumes:
  postgres_storage:
