services:
  ryot-db:
    image: "postgres"
    restart: "unless-stopped"
    container_name: "ryot-db"
    # Uncomment the volume type for your deployment:
    # volumes:
    #   - type: "volume"
    #     source: "ryot_storage"
    #     target: "/var/lib/postgresql/"
    #   - type: "bind"
    #     source: "./ryot/data/"
    #     target: "/var/lib/postgresql/"
    environment:
      TZ: "${TZ:-Etc/UTC}"
      POSTGRES_PASSWORD: "postgres"
      # Defaults you can optionally override:
      # POSTGRES_DB: "postgres"
      # POSTGRES_USER: "postgres"

  ryot:
    image: "ghcr.io/ignisda/ryot"
    # pull_policy: "always"
    container_name: "ryot"
    depends_on:
      - "ryot-db"
    restart: "unless-stopped"
    ports:
      - "${LAN_IP:-127.0.0.1}:${RYOT_PORT:-8000}:8000"
    environment:
      TZ: "${TZ:-Etc/UTC}"
      DATABASE_URL: "postgres://postgres:postgres@ryot-db:5432/postgres" # REQUIRED
      # Generate a random value securely:
      #     $ docker run --rm --entrypoint sh "ghcr.io/ignisda/ryot" \
      #     -c 'tr -dc "a-zA-Z0-9" < "/dev/urandom" | head -c "20" ; echo'
      SERVER_ADMIN_ACCESS_TOKEN: >-
        ${SERVER_ADMIN_ACCESS_TOKEN:?Must set to secure random string!}
      # Optional configuration:
      # FRONTEND_URL: "https://ryot.your-domain.com" # IP address is fine too
      DISABLE_TELEMETRY: "true"

# Uncomment if using 'type: "volume"' above:
# volumes:
#   ryot_storage:
